#+TITLE: Additional instructions for using the org template
#+AUTHOR: Frédéric Santos

* Main text
- ~main.org~ should contain the main text of your manuscript.
- In the header of ~main.org~, indicate the recommender's name and the reviewers' names according to the information sent back to you by the PCI team (lines 9-10).
- The file ~preambule_entomol.tex~ should be modified to select badges: choose the badges "Open Code" and "Open Data" only if appropriate (in addition to the "Open Access" and "Open Peer-Review" badges). If they are not appropriate, comment the lines 87 and 89 in ~preambule_entomol.tex~.

* Bibliography
- ~biblio.bib~ should contain your references in BibTeX format (possibly exported from Zotero using the [[https://github.com/retorquere/zotero-better-bibtex][BetterBibTeX]] plugin).
- In ~main.org~, I use the LaTeX package ~apacite~, so that by default the [[https://apastyle.apa.org/][APA style]] will be used as bibliography style. This is especially convenient for /PCI Archaeo/ and /PCI Paleo/, which suggests this style. For other PCI journals, if you want to use another bibliography style, simply remove this package and set another style instead in line 80 of ~main.org~. For instance, the styles ~plain~ or ~plainnat~ should be well suited for /PCI MCB/.
- In the file ~preambule_entomol.tex~, you'll also have to provide a correct reference for your own manuscript (line 97).

* Improvements
- Do not hesitate to modify the LaTeX template as you want (and send it back to the PCI team if you made significant improvements).
